info:
  profile: dev
  from: git
  password: '{cipher}AQBi0CVqQjXYsIk7CBjVkSewgKOk2eLdujxLyBA1O0HkF0JovN1R6H4/vZTbGIRN5OIS0NoVOjszKiIJ2hnlq3RJeYfV7A/u2S/Evw17sIjW0/CGuBTcgtqF3rqEP0qtJul6eju5xX9mwQAELvYf2gUiYWks57oSgZ7Yw6roUAHXopINksPX535cBCg4E0iKMHamLLmF3VFbO7KirrLCnnCgnWuF3FWSUtqKS1olno6DtIC6DMXp5Z9ZdsJ2pQhBUxJQDPh8U0M/PTzUjGyMwt5pytO0ZcsKmiFabfercomKxYjlw/68ENMPfRbN6mBTK6be9xhCsIDv2qLamBirvlU03SFFHPVaEDqDrYVwqbJkz5J1Q8kI5oe26UfhuM/64='
